# Generated by Django 3.1.4 on 2020-12-21 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250, unique=True)),
                ('team_players', models.CharField(max_length=1000)),
                ('team_coach', models.CharField(max_length=250)),
                ('team_manager', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('team_a_points', models.IntegerField(null=True)),
                ('team_b_points', models.IntegerField(null=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teama', to='football_tournament.teams')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamb', to='football_tournament.teams')),
            ],
        ),
    ]
