# Generated by Django 3.1.4 on 2020-12-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_name',
            field=models.CharField(max_length=250),
        ),
    ]
