# Generated by Django 3.1.4 on 2020-12-22 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_tournament', '0002_auto_20201222_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammatches',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_tournament.teams'),
        ),
    ]
